---
- name: GCP Multi Subnet Provisioning Workflow
  hosts: localhost
  gather_facts: no

  # Load all variables
  vars_files:
    - vars/common.yml
    - vars/paths.yml
    - vars/email.yml
    - vars/vault.yml    # optional, if you use vault for secrets

  # Input variable coming from user JSON or CLI
  # Example:
  # ansible-playbook main.yml -e subnets="[{'RegionCode':'AO','Env':'pr','Solution':'sap','SubnetSize':27,'VPC':'test','Comments':'Auto'}]"
  
  roles:
    - gcp_subnet_multi
